// ────────────────────────────────────────────────────────────────────────────
// Mock achievements data.
// Each achievement has an id, title, description, icon, category, rarity,
// progress (current/target), and earnedAt (null if locked).
// ────────────────────────────────────────────────────────────────────────────

export const ACHIEVEMENT_CATEGORIES = [
  "All",
  "Streaks",
  "Consistency",
  "Categories",
  "Special",
];

export const RARITY = {
  common: { label: "Common", color: "#8b8b99", glow: "rgba(139,139,153,0.3)" },
  rare: { label: "Rare", color: "#0ea5e9", glow: "rgba(14,165,233,0.35)" },
  epic: { label: "Epic", color: "#a855f7", glow: "rgba(168,85,247,0.4)" },
  legendary: {
    label: "Legendary",
    color: "#f59e0b",
    glow: "rgba(245,158,11,0.45)",
  },
};

export const mockAchievements = [
  // ─── Streaks ──────────────────────────────────────────────────────────
  {
    id: "streak-3",
    title: "Getting Started",
    description: "Maintain a 3-day streak on any habit.",
    icon: "🔥",
    category: "Streaks",
    rarity: "common",
    progress: { current: 3, target: 3 },
    earnedAt: "2026-04-18",
    tip: "Pick one small habit and do it for 3 days straight.",
  },
  {
    id: "streak-7",
    title: "7-Day Warrior",
    description: "Maintain a 7-day streak on any habit.",
    icon: "⚔️",
    category: "Streaks",
    rarity: "common",
    progress: { current: 7, target: 7 },
    earnedAt: "2026-04-24",
    tip: "Consistency beats intensity. Show up every day for a week.",
  },
  {
    id: "streak-14",
    title: "Two-Week Champion",
    description: "Maintain a 14-day streak on any habit.",
    icon: "🏅",
    category: "Streaks",
    rarity: "rare",
    progress: { current: 14, target: 14 },
    earnedAt: "2026-05-01",
    tip: "The second week is the hardest — push through!",
  },
  {
    id: "streak-30",
    title: "30-Day Legend",
    description: "Maintain a 30-day streak on any habit.",
    icon: "👑",
    category: "Streaks",
    rarity: "epic",
    progress: { current: 22, target: 30 },
    earnedAt: null,
    tip: "You're 73% there! Keep showing up every day.",
  },
  {
    id: "streak-60",
    title: "Iron Will",
    description: "Maintain a 60-day streak on any habit.",
    icon: "💎",
    category: "Streaks",
    rarity: "legendary",
    progress: { current: 22, target: 60 },
    earnedAt: null,
    tip: "This takes serious dedication. Automate your habit trigger.",
  },

  // ─── Consistency ──────────────────────────────────────────────────────
  {
    id: "perfect-week",
    title: "Perfect Week",
    description: "Complete 100% of your habits for an entire week.",
    icon: "⭐",
    category: "Consistency",
    rarity: "rare",
    progress: { current: 5, target: 7 },
    earnedAt: null,
    tip: "You're averaging 5/7 days. Focus on weekends!",
  },
  {
    id: "perfect-day-5",
    title: "Five Perfect Days",
    description: "Have 5 days where you complete every single habit.",
    icon: "✨",
    category: "Consistency",
    rarity: "common",
    progress: { current: 5, target: 5 },
    earnedAt: "2026-05-10",
    tip: "Complete all habits in a single day, five times total.",
  },
  {
    id: "monthly-master",
    title: "Monthly Master",
    description: "Achieve 90%+ completion rate for an entire month.",
    icon: "📅",
    category: "Consistency",
    rarity: "epic",
    progress: { current: 78, target: 90 },
    earnedAt: null,
    tip: "You're at 78% this month. Cut low-priority habits if needed.",
  },
  {
    id: "comeback-kid",
    title: "Comeback Kid",
    description: "Recover a broken streak and rebuild it to 7+ days.",
    icon: "🔄",
    category: "Consistency",
    rarity: "rare",
    progress: { current: 1, target: 1 },
    earnedAt: "2026-05-08",
    tip: "Break a streak, then build it back stronger.",
  },
  {
    id: "no-zero-days",
    title: "No Zero Days",
    description: "Complete at least one habit every day for 14 days.",
    icon: "🎯",
    category: "Consistency",
    rarity: "common",
    progress: { current: 14, target: 14 },
    earnedAt: "2026-05-12",
    tip: "Even completing just one habit counts. Never go to zero.",
  },

  // ─── Categories ───────────────────────────────────────────────────────
  {
    id: "fitness-fanatic",
    title: "Fitness Fanatic",
    description: "Complete fitness habits 30 times.",
    icon: "💪",
    category: "Categories",
    rarity: "rare",
    progress: { current: 30, target: 30 },
    earnedAt: "2026-05-15",
    tip: "Keep crushing those workouts!",
  },
  {
    id: "mindful-master",
    title: "Mindful Master",
    description: "Complete mindfulness habits 20 times.",
    icon: "🧘",
    category: "Categories",
    rarity: "rare",
    progress: { current: 18, target: 20 },
    earnedAt: null,
    tip: "Just 2 more mindfulness completions to go!",
  },
  {
    id: "bookworm",
    title: "Bookworm",
    description: "Complete reading habits 25 times.",
    icon: "📚",
    category: "Categories",
    rarity: "rare",
    progress: { current: 25, target: 25 },
    earnedAt: "2026-05-18",
    tip: "Read every day — even 10 minutes counts.",
  },
  {
    id: "hydration-hero",
    title: "Hydration Hero",
    description: "Complete water habits 30 times.",
    icon: "💧",
    category: "Categories",
    rarity: "common",
    progress: { current: 30, target: 30 },
    earnedAt: "2026-05-05",
    tip: "Water is life! Keep the streak going.",
  },
  {
    id: "well-rounded",
    title: "Well Rounded",
    description: "Have active habits in 4+ different categories.",
    icon: "🌈",
    category: "Categories",
    rarity: "epic",
    progress: { current: 5, target: 4 },
    earnedAt: "2026-04-20",
    tip: "Diversify your habits across health, learning, fitness, etc.",
  },

  // ─── Special ──────────────────────────────────────────────────────────
  {
    id: "first-step",
    title: "First Step",
    description: "Create your very first habit.",
    icon: "🚀",
    category: "Special",
    rarity: "common",
    progress: { current: 1, target: 1 },
    earnedAt: "2026-03-15",
    tip: "Every journey begins with a single step.",
  },
  {
    id: "century-club",
    title: "Century Club",
    description: "Reach 100 total habit completions.",
    icon: "💯",
    category: "Special",
    rarity: "epic",
    progress: { current: 100, target: 100 },
    earnedAt: "2026-05-14",
    tip: "You've hit triple digits! Incredible dedication.",
  },
  {
    id: "habit-collector",
    title: "Habit Collector",
    description: "Create 5 different habits.",
    icon: "🗂️",
    category: "Special",
    rarity: "common",
    progress: { current: 7, target: 5 },
    earnedAt: "2026-04-02",
    tip: "Build a diverse set of habits to cover all life areas.",
  },
  {
    id: "weekend-warrior",
    title: "Weekend Warrior",
    description: "Complete all habits on both Saturday and Sunday.",
    icon: "🏖️",
    category: "Special",
    rarity: "rare",
    progress: { current: 0, target: 1 },
    earnedAt: null,
    tip: "Weekends are where most streaks break. Beat the odds!",
  },
  {
    id: "triple-threat",
    title: "Triple Threat",
    description: "Have 3 simultaneous active streaks of 7+ days.",
    icon: "🔱",
    category: "Special",
    rarity: "legendary",
    progress: { current: 2, target: 3 },
    earnedAt: null,
    tip: "You have 2 active 7-day streaks. One more to go!",
  },
];
